export const appRoutes = {
  home: "/",
  trial: "/trial",
  auth: {
    login: "/?auth=login",
    register: "/?auth=register",
  },
  admin: {
    dashboard: "/admin",
    analytics: "/admin/analytics",
    grades: "/admin/grades",
    subjects: "/admin/subjects",
    questions: "/admin/questions",
    packages: "/admin/packages",
    subscriptions: "/admin/subscriptions",
    lessPrivate: "/admin/lessPrivate",
    teacher: "/admin/teacher",
    teacherExams: "/admin/teacher/exams",
    teacherExamDetail: (id: string) => `/admin/teacher/exams/${id}`,
    teacherMonitor: "/admin/teacher/monitor",
    teacherMonitorDetail: (id: string) => `/admin/teacher/monitor/${id}`,
    teacherResults: "/admin/teacher/results",
  },
  student: {
    dashboard: "/student",
    trial: "/student/trial",
    packages: "/student/packages",
    packageDetail: (id: string) => `/student/packages/${id}`,
    recap: "/student/recap",
    subscription: "/student/subscription",
    discussion: "/student/discussion",
    lessPrivate: "/student/lessPrivate",
  },
  teacher: {
    dashboard: "/teacher",
    exams: "/teacher/exams",
    examDetail: (id: string) => `/teacher/exams/${id}`,
    monitor: "/teacher/monitor",
    monitorDetail: (id: string) => `/teacher/monitor/${id}`,
    results: "/teacher/results",
  },
};
