import { BookOpenCheck, CalendarDays, GraduationCap, Lock, Sparkles, Clipboard } from "lucide-react";

export type PackagePreviewAction = "free" | "register" | "coming-soon" | "development";

export const previewPackages = [
  {
    title: "Free",
    price: "Rp0",
    meta: "Coba alur latihan My Exam sebelum register.",
    features: ["10 soal publik tanpa login", "1 paket free setelah register", "Cocok untuk mencoba fitur dasar"],
    Icon: BookOpenCheck,
    badge: "Starter",
    tone: "slate",
    action: "free" as const,
    actionLabel: "Mulai Gratis",
  },
  {
    title: "Subscription Siswa 1 Bulan",
    price: "Rp39.000",
    meta: "Cocok untuk persiapan intensif menjelang ujian.",
    features: ["Akses semua paket premium", "Pembahasan video", "Recap nilai selama 30 hari"],
    Icon: CalendarDays,
    badge: "Paling Populer",
    tone: "violet",
    action: "register" as const,
    actionLabel: "Daftar Sekarang",
  },
  {
    title: "Subscription Siswa 3 Bulan",
    price: "Rp99.000",
    meta: "Lebih hemat untuk latihan bertahap sampai siap.",
    features: ["Semua fitur premium", "Masa aktif 90 hari", "Persiapan jangka panjang"],
    Icon: Sparkles,
    badge: "Paling Hemat",
    tone: "amber",
    action: "register" as const,
    actionLabel: "Daftar Sekarang",
  },
  {
    title: "Paket Premium 3",
    price: "Segera hadir",
    meta: "Paket lanjutan untuk drilling per materi.",
    features: ["Pembahasan mendalam", "Latihan tambahan", "Target skor lebih tinggi"],
    Icon: Lock,
    badge: "Segera Hadir",
    tone: "violet",
    action: "coming-soon" as const,
    actionLabel: "Segera Hadir",
  },
  {
    title: "Booking Les Private",
    price: "Dalam pengembangan",
    meta: "Pendampingan belajar personal bersama pengajar.",
    features: ["Pilih jadwal belajar", "Bahas materi yang sulit", "Sesi belajar lebih personal"],
    Icon: GraduationCap,
    badge: "Dalam Pengembangan",
    tone: "sky",
    action: "development" as const,
    actionLabel: "Dalam Pengembangan",
  },
  {
    title: "Mode Ujian Online",
    price: "49.000",
    meta: "Fitur khusus untuk guru yang ingin mencoba ujian online.",
    features: ["Pembahasan mendalam", "Latihan tambahan", "Target skor lebih tinggi"],
    Icon: Clipboard,
    badge: "Khusus Guru",
    tone: "violet",
    action: "register" as const,
    actionLabel: "Coba Sekarang",
  }
];
